---
title: "Tarea 1. Soluciones de ecuaciones"
author: "Jocelyn Padilla M"
format: 
  html:
    grid:
      body-width: 1200px
lang: es
---

Importamos packages y funciones necesarias:

```{python}
import matplotlib.pyplot as plt
import numpy as np
from scipy import optimize
```

Para las funciones de los ejercicios 1-6 realiza lo siguiente:

a)  Gráfica de la función en el intervalo en caso que se indique.

b)  Aproximación de la raíz o raíces por medio de los métodos de bisección, Newton-Raphson y la secante.

c)  Compara los resultados.

::: {#exr-tarea1_1}
Un polinomio cuadrático de la forma $f(x)=ax^2+bx+c$ con dos raíces reales distintas.
:::

::: {#exr-tarea1_2}
Un polinomio cúbico de la forma $f(x)=ax^3+bx^2+cx+d$ con tres raíces reales distintas.
:::


::: {#exr-tarea1_3}
$f(x)= x^3 -5x^2e^{-x}+e^{-3x}$, para $0\leq x \leq 2$

**Gráfica de la función** 

```{python}
#| code-fold: true

f = lambda x: x**3-5* x**2 * np.exp(-x) + np.exp(-3*x) 

x = np.linspace(0, 2, 100)
y = f(x) 

# Crear gráfica
plt.figure(figsize=(8,6)) # Tamaño en pulgadas
plt.plot(x,y, color ="red") 
plt.axhline(0, color = "black", linewidth = 0.8, linestyle = "--") #Eje x
plt.axvline(0, color = "black", linewidth = 0.8, linestyle = "--") #Eje x

# Personalizar gráfica
plt.title(r"Gráfica del ejercicio 1", fontsize= 14)
plt.xlabel("x")
plt.ylabel("y")
plt.grid()

plt.show()
```

Hay dos raices...

**Aproximación de la primera raíz por el método de la bisección** 

```{python}
raíz_b, raízb_info = optimize.bisect(f, 0, 1, full_output=True) 

print("Método de la bisección")
print(raízb_info)
print("------------------")
print(f"La primera raíz por el método de la bisección es: {raíz_b}") 
```

**Aproximación de la primera raíz por el método de Newton-Raphson**

La dervidad de la función es: 
$f'(x) = 3x^2+5xe^(-x)$

```{python} 
df = lambda x: 3* x**2 + 5*x*np.exp(-x)*(x-2) - 3 * np.exp(-3*x) 

raiz_n, raizn_info = optimize.newton(f, x0=0, fprime= df, full_output=True) 

print("Método de Newton")
print(raizn_info)
print("------------------")
print(f"La primera raíz por el método de Newton-Ralph es: {raiz_n}") 
```

**Aproximación de la primera raíz por el método de la secante**



**Aproximación de la segunda raíz por el método de la biseccion**

La dervidad de la función es: 
$f'(x) = 3x^2+5xe^(-x)$

```{python} 
raíz2_b, raíz2b_info = optimize.bisect(f, 1, 1.75, full_output=True) 

print("Método de la bisección")
print(raíz2b_info)
print("------------------")
print(f"La segunda raíz por el método de la bisección es: {raíz2_b}") 
```

**Aproximación de la segunda raíz por el método de Newton-Raphson**

```{python}
#| code-fold: true
df = lambda x: 3* x**2 + 5*x*np.exp(-x)*(x-2) - 3 * np.exp(-3*x) 

raiz2_b, raiz2b_info = optimize.newton(f, x0= 2, fprime= df, full_output=True) 

print("Método de biseccion")
print(raiz2b_info)
print("------------------")
print(f"La segunda raíz por el método de la bisección es: {raiz2_b}") 
```





:::


::: {#exr-tarea1_4}
La primera raíz positiva de $g(x)= e^{-x}-cos(ax)$ para $a=1, 3, 5, 9$.
:::

::: {#exr-tarea1_5}
$g(x)= e^x-log(x+1) -b$ donde $b=2, 3, 5$.
:::

::: {#exr-tarea1_6}
Todas las raíces de $f(x)= \sqrt{x}-sen(x) -c$ para $c=1,\pi$.

**Gráfica de la función** 

```{python}
#| code-fold: true

f = lambda x,c: np.sqrt(x)-np.sin(x)-c  

x = np.linspace(0, 40, 500)
y1 = f(x, 1) 
y2 = f(x, np.pi) 

# Crear gráfica
plt.figure(figsize=(8,6)) # Tamaño en pulgadas
plt.plot(x,y1, color ="#ABC111", label = "c=1")
plt.plot(x, y2, color = "red", label = "c = pi")
plt.axhline(0, color = "black", linewidth = 0.8, linestyle = "--") #Eje x
plt.axvline(0, color = "black", linewidth = 0.8, linestyle = "--") #Eje x
plt.legend(fontsize= 14)

# Personalizar gráfica
plt.title(r"Gráfica del ejercicio 6", fontsize= 12)
plt.xlabel("x")
plt.ylabel("y")
plt.grid()

plt.show()
```

**Aproximación de la raíz para c=1 por el método de Newton-Raphson**


```{python}
#| code-fold: true
df = lambda x: 1/(2*np.sqrt(x))-np.cos(x)

raiz_n, raizn_info = optimize.newton(f, x0=4, fprime =df,full_output=True) 

print("Método de Newton Raphson") 
print(raizn_info) 
print("--------------")
print(f"La aproximacion de la raiz por el método de Newton-Raphson es: {raiz_n}") 
```



**Aproximación de raíz para c=1 por el método de la bisección** 

```{python}

f = lambda x: np.sqrt(x)-np.sin(x)-1 

raíz_b, raízb_info = optimize.bisect(f, 0, 5,  full_output=True) 

print("Método de la bisección")
print(raízb_info)
print("------------------")
print(f"La raíz para c=1 por el método de la bisección es: {raíz_b}") 
```

**Aproximación de la primera raíz por el método de la secante**

```{python}
raiz_s, raizs_info = optimize.newton(f, x0=1, x1=4, full_output= True) 

print("Método de la secante") 
print(raizs_info)
print("-------------")
print(f"La aproximación de la raíz por el método de la secante es: {raiz_s}")  
```

**Raíces para $c=\pi$** 

::: {.panel-tabset} 
## 1era raíz 

```{python}
#| code-fold: true
f = lambda x: np.sqrt(x)-np.sin(x)-np.pi 

rb, rinfob = optimize.bisect(f, 2, 5, full_output=True) 
rn, rinfon=optimize.newton(f, x0=2, x1= 4,  fprime= df, full_output=True) 

print(f"Raiz bisección: {rb}") 
print(f"Raiz Newton: {rn}") 
print(f"Raiz secante: {rs}") 
```

::: {.panel-tabset} 
## 2da raíz 

```{python}
#| code-fold: true
f = lambda x: np.sqrt(x)-np.sin(x)-np.pi 

rb, rinfob = optimize.bisect(f, 5, 7, full_output=True) 
rn, rinfon=optimize.newton(f, x0=6, fprime= df,  fprime= df, full_output=True)
rs, rinfos= optimize.newton(f x0=5, x1=7,  full_output=True) 

print(f"Raiz bisección: {rb}") 
print(f"Raiz Newton: {rn}") 
print(f"Raiz secante: {rs}") 
```

## Secante 


:::

::: {#exr-tarea1_7}
El sistema de ecuaciones no lineales:

\begin{eqnarray}
y^2 - x^2 + 4x - 2 &=& 0\\
x^2 +3y^2 - 4 &=& 0\\
\end{eqnarray}

tiene dos soluciones. Realiza una gráfica de las curvas de nivel y aproxima las soluciones.


:::

::: {#exr-tarea1_8}
Considera el siguiente sistema:

\begin{eqnarray}
sen(x) + y^2 - 1 &=& 0\\
x + cos(y) - 1 &=& 0\\
\end{eqnarray}

Realiza una gráfica de las curvas de nivel y aproxima la solución con la función `fsolve`.
:::

::: {#exr-tarea1_9}
Para el siguiente sistema de ecuaciones no lineal:

\begin{eqnarray}
x^3 + y - 6 &=& 0\\
y^3 -x - 4 &=& 0\\
\end{eqnarray}

Realiza una gráfica de las curvas de nivel y aproxima la solución con la función `fsolve`.
:::

::: {#exr-tarea1_10}
Consideraremos un sistema de ecuaciones no lineal para describir un modelo de equilibrio económico.

1.  Curva de demanda no lineal

\begin{equation}
q_d = 200 - 10 p^2
\end{equation}

2.  Curva de oferta no lineal

\begin{equation}
q_s = 5 p^3 + 15
\end{equation}

El equilibrio ocurre cuando

\begin{equation}
q_s = q_d
\end{equation}

O bien

\begin{eqnarray}
q + 10p^2 -200  &=& 0\\
q - 5p^3 - 15 &=& 0\\
\end{eqnarray}

Realiza una gráfica de las curvas y aproxima el punto de equilibrio con la función `fsolve`.
:::